Repository pagopa/pagopa-mbd, pull requests merged in 2025-03, with the labels that each got.

#4 feat: [PAGOPA-2750] Implement workload identity
  .github/workflows/01_add_patch_label.yml
  .github/workflows/02_check_pr.yml
  .github/workflows/03_code_review.yml
  .github/workflows/04_release_deploy.yml
  .github/workflows/04h_deploy_with_github_runner.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/01_github_environment.tf
  .identity/99_main.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, skip

#3 [PAGOPA-2749] make service work
  .identity/00_data.tf
  .identity/01_github_environment.tf
  Dockerfile
  docker/run_docker.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/env/weu-dev/backend.tfvars
  infra/env/weu-dev/terraform.tfvars
  infra/env/weu-prod/backend.tfvars
  infra/env/weu-prod/terraform.tfvars
  infra/env/weu-uat/backend.tfvars
  infra/env/weu-uat/terraform.tfvars
  infra/policy/_base_policy.xml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/mbd/config/CosmosDBConfig.java
  src/main/java/it/gov/pagopa/mbd/config/RequestFilter.java
  src/main/java/it/gov/pagopa/mbd/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/mbd/exception/MBDReportingException.java
  src/main/java/it/gov/pagopa/mbd/repository/BizEventRepository.java
  src/main/java/it/gov/pagopa/mbd/service/GenerateReportingService.java
  src/main/java/it/gov/pagopa/mbd/util/CacheInstitutionData.java
  src/main/resources/application.yml
  src/test/resources/application.properties
Labels: enhancement, size/large, patch

#5 feat: Upd-helm-deploy
  .github/workflows/04_deploy_with_github_runner.yml
  .github/workflows/04_release_deploy.yml
  .github/workflows/cd_deploy_with_github_runner.yml
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: patch

#6 chore: Update README.md
  README.md
Labels: skip, ignore-for-release
