Repository pagopa/pagopa-mbd, pull requests merged in 2025-06, with the labels that each got.

#8 [PIDM-492] feat: Upgrade helm to v 7.5.0
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#9 Pagopa 3017 save retry csv
  .github/workflows/03_code_review.yml
  .gitignore
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/mbd/Application.java
  src/main/java/it/gov/pagopa/mbd/config/RetryConfig.java
  src/main/java/it/gov/pagopa/mbd/config/RetryExecutor.java
  src/main/java/it/gov/pagopa/mbd/config/ScheduledJobsConfig.java
  src/main/java/it/gov/pagopa/mbd/controller/RecoveryController.java
  src/main/java/it/gov/pagopa/mbd/exception/MBDRetryException.java
  src/main/java/it/gov/pagopa/mbd/service/GenerateReportingService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/it/gov/pagopa/mbd/GenerateReportingServiceTest.java
  src/test/java/it/gov/pagopa/mbd/RetryExecutorTest.java
  src/test/java/it/gov/pagopa/mbd/service/GenerateReportingServiceTest.java
  src/test/java/it/gov/pagopa/mbd/utils/TestUtils.java
Labels: enhancement, size/large, minor

#10 feat: PAGOPA-3019 add helm cron blueprint
  .github/workflows/04_deploy_with_github_runner.yml
  .github/workflows/cd_deploy_with_github_runner.yml
  .gitignore
  .terraform-version
  helm/Chart.lock
  helm/Chart.yaml
  helm/scripts/README.md
  helm/scripts/get-elab-ricevute.sh
  helm/scripts/init.sh
  helm/scripts/renametransfer.sh
  helm/scripts/runflussi.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/99_main.tf
  openapi/openapi.json
  pom.xml
Labels: size/large, patch
